# Generated by Django 5.1.1 on 2024-10-08 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiwaka', '0002_remove_order_products_orderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='orderitem',
            name='ingredients',
            field=models.ManyToManyField(blank=True, to='wiwaka.ingredient'),
        ),
    ]
