# Generated by Django 5.1.1 on 2024-10-08 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiwaka', '0003_ingredient_orderitem_ingredients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='ingredients',
        ),
        migrations.CreateModel(
            name='OrderItemIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wiwaka.ingredient')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_item_ingredients', to='wiwaka.orderitem')),
            ],
        ),
    ]
