# Generated by Django 5.1.1 on 2024-10-08 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiwaka', '0004_remove_orderitem_ingredients_orderitemingredient'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='ingredients',
            field=models.ManyToManyField(related_name='order_items', through='wiwaka.OrderItemIngredient', to='wiwaka.ingredient'),
        ),
        migrations.AlterField(
            model_name='orderitemingredient',
            name='status',
            field=models.CharField(max_length=20),
        ),
    ]
