# Generated by Django 5.1.1 on 2024-10-09 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiwaka', '0006_remove_order_status_order_ingredients_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitemingredient',
            name='order_item',
        ),
        migrations.RemoveField(
            model_name='orderitemingredient',
            name='ingredient',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='ingredients',
            new_name='order_details',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
        migrations.DeleteModel(
            name='OrderItemIngredient',
        ),
    ]
