# Generated by Django 5.1.1 on 2024-10-10 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiwaka', '0007_remove_orderitemingredient_order_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(default='მზადდება'),
        ),
    ]
