# Generated by Django 5.1.1 on 2024-10-10 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiwaka', '0008_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
